### ISSUE TITLE
[UI] - Box on the bottom right of try.html has headers of improper length

### ISSUE THREAD

**Issue by anshumanv** [status-im/pluto#102]
`Components` heading is only of limited width and whitespace comes in as we horizontally scroll as depicted in the screenshot, please feel free to close this if it's intentional

![screenshot from 2018-11-29 20-19-08](https://user-images.githubusercontent.com/21009455/49229896-7be61680-f414-11e8-8c83-b4bfb6dbc7d1.png)

Will fix this issue if it's valid

**Comment by jeluard** [comment]
Sounds like a valid issue!

**Comment by anshumanv** [comment]
Aight, PR coming up. :sparkles:
