### ISSUE TITLE
Make install button more obvious

### ISSUE THREAD

**Issue by pablanopete** [status-im/pluto#124]
Right now the install buttons on a pluto example are not very obvious to a mobile user

It would be great to have a easier to read mobile responsive button here 

(Example + pic)
https://status-im.github.io/pluto/try.html?hash=QmcfsYnFvKXApcFTCNttpQvQKYxiMCqVx5MvsocFyrr2KA

<img width="319" alt="screen shot 2019-01-08 at 4 18 03 pm" src="https://user-images.githubusercontent.com/18363825/50862392-241ac380-1361-11e9-996a-c2346d881c5e.png">
^ Universal link and IPFS are tiny on mobile

**Comment by jeluard** [comment]
The playground is useful for people who wants to modify an extension. I would expect this to happen on desktop only.
To distribute an extension you would probably not use it.
