### ISSUE TITLE
Getting started hyperlink broken 

### ISSUE THREAD

**Issue by StatusSceptre** [status-im/pluto#130]
https://status-im.github.io/pluto/docs/Tutorial

Linked on main page 
<img width="259" alt="screen shot 2019-01-28 at 8 32 55 pm" src="https://user-images.githubusercontent.com/42685581/51880191-f3b0be80-233b-11e9-823c-c0ebad731c11.png">

**Comment by jeluard** [comment]
@StatusSceptre Thanks! Fixed :)
