### ISSUE TITLE
Proofread docs and fix grammar

### ISSUE THREAD

**Issue by krisc** [status-im/pluto#133]
@StatusSceptre  When I was working on  https://github.com/status-im/status-react/issues/7103 and reading up on the docs for Pluto, I noticed a lot of grammatical errors and awkward sentences. Perhaps the author of the docs isn't a native English speaker. If the team would like to put a bounty on proofreading, rewriting, and editing these docs then I would gladly take on fulfilling that.

**Comment by StatusSceptre** [comment]
Sure! Would you mind fixing some examples to start, what would be especially helpful is updating documentation as it rolls down the pipeline and helping out with that if you’re interested?

**Comment by jeluard** [comment]
@krisc The latest doc is actually located [here](https://status.im/extensions/). I will remove the older one, thanks for the reminder!

Something that would be useful is to update https://status.im/extensions/reference_views.html so that it reflect the latest improvements. WDYT?

**Comment by jeluard** [comment]
@krisc You can find them [here](https://github.com/status-im/status-react/blob/develop/src/status_im/extensions/core.cljs#L403)

**Comment by krisc** [comment]
@jeluard Thanks!

@StatusSceptre Should an issue/bounty be made for this, or should I just submit a PR once done?

**Comment by StatusSceptre** [comment]
Issue and bounty would be fine! If you create an issue and estimate of time it should take you will be glad to get a bounty on this.

**Comment by krisc** [comment]
@StatusSceptre @jeluard oh, and which repo is the newest doc in? Doesn't look like it's in this one.

**Comment by jeluard** [comment]
@krisc You can find the source [here](https://github.com/status-im/status.im/blob/develop/source/extensions/reference_events.md)
