### ISSUE TITLE
Improve let symbol replacement logic

### ISSUE THREAD

**Issue by jeluard** [status-im/pluto#63]
Let blocks replace symbols with their associated values using a dumb logic.

Make sure this logic only replaces symbols that should be replaced (e.g. not view components, blocks symbols, ..).

Also make sure that nested let blocks properly works (shadowing, niling symbols defined in nested blocks, ..)

**Comment by bhauman** [comment]
This has been fixed by 3de45662231dd2a1c5a4135e45b239909f128841
